name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint the commit
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: '.commitlintrc.js'
